# Generated by Django 3.1.5 on 2021-01-23 21:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myblog',
            name='image',
        ),
        migrations.RemoveField(
            model_name='myblog',
            name='url',
        ),
        migrations.AddField(
            model_name='myblog',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
