# Generated by Django 3.1.5 on 2021-01-23 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210123_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myblog',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
