# Generated by Django 3.1.5 on 2021-01-17 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='MyProject',
        ),
    ]
